name: 'ai_analytics'
version: '1.0.0'
config-version: 2

profile: 'ai_analytics'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
clean-targets: ["target", "dbt_packages"]

models:
  ai_analytics:
    silver:
      +materialized: table
      +schema: silver
      staging:
        +materialized: view
        +schema: staging
    gold:
      +materialized: table
      +schema: gold
      +grants:
        select: ['analytics_reader']
